import {
  SiPython, SiGithub, SiFigma, SiAdobephotoshop, SiGooglecloud, SiNotion,
  SiCanva, SiHubspot, SiGoogleads, SiMeta, SiZapier, SiSalesforce, SiTiktok,
  SiInstagram, SiJira, SiVercel, SiObsstudio, SiDiscord, SiStripe, SiShopify,
  SiMailchimp, SiAnthropic, SiSemrush, SiApollographql, SiFacebook, SiSlack, SiOpenai,
} from 'react-icons/si';
import { FaDatabase, FaRobot, FaStore, FaBullseye, FaFunnelDollar, FaPaintBrush, FaLayerGroup } from 'react-icons/fa';
import { RiClapperboardFill, RiMicrosoftFill } from 'react-icons/ri';
import { TbBrandZoom } from 'react-icons/tb';

export type Skill = { label: string; icon: (size: number) => React.ReactNode };

export const SKILLS: Skill[] = [
  { label: 'SQL',                  icon: (s) => <FaDatabase size={s} />          },
  { label: 'Python',               icon: (s) => <SiPython size={s} />            },
  { label: 'Prompt Eng.',          icon: (s) => <FaRobot size={s} />             },
  { label: 'Figma',                icon: (s) => <SiFigma size={s} />             },
  { label: 'Photoshop',            icon: (s) => <SiAdobephotoshop size={s} />    },
  { label: 'GitHub',               icon: (s) => <SiGithub size={s} />            },
  { label: 'Google Cloud',         icon: (s) => <SiGooglecloud size={s} />       },
  { label: 'Notion',               icon: (s) => <SiNotion size={s} />            },
  { label: 'Canva',                icon: (s) => <SiCanva size={s} />             },
  { label: 'HubSpot',              icon: (s) => <SiHubspot size={s} />           },
  { label: 'Google Ads',           icon: (s) => <SiGoogleads size={s} />         },
  { label: 'Meta Ads',             icon: (s) => <SiMeta size={s} />              },
  { label: 'E-Commerce',           icon: (s) => <FaStore size={s} />             },
  { label: 'Zapier',               icon: (s) => <SiZapier size={s} />            },
  { label: 'Salesforce',           icon: (s) => <SiSalesforce size={s} />        },
  { label: 'Content Creation',     icon: (s) => <RiClapperboardFill size={s} />  },
  { label: 'TikTok',               icon: (s) => <SiTiktok size={s} />            },
  { label: 'Instagram',            icon: (s) => <SiInstagram size={s} />         },
  { label: 'Clay',                 icon: (s) => <FaBullseye size={s} />          },
  { label: 'Apollo',               icon: (s) => <SiApollographql size={s} />     },
  { label: 'ZoomInfo',             icon: (s) => <TbBrandZoom size={s} />         },
  { label: 'Jira',                 icon: (s) => <SiJira size={s} />              },
  { label: 'Vercel',               icon: (s) => <SiVercel size={s} />            },
  { label: 'OBS',                  icon: (s) => <SiObsstudio size={s} />         },
  { label: 'CapCut',               icon: (s) => <RiClapperboardFill size={s} />  },
  { label: 'Discord',              icon: (s) => <SiDiscord size={s} />           },
  { label: 'Stripe',               icon: (s) => <SiStripe size={s} />            },
  { label: 'Shopify',              icon: (s) => <SiShopify size={s} />           },
  { label: 'Mailchimp',            icon: (s) => <SiMailchimp size={s} />         },
  { label: 'Claude',               icon: (s) => <SiAnthropic size={s} />         },
  { label: 'SEMrush',              icon: (s) => <SiSemrush size={s} />           },
  { label: 'Facebook',             icon: (s) => <SiFacebook size={s} />          },
  { label: 'Microsoft',            icon: (s) => <RiMicrosoftFill size={s} />     },
  { label: 'Attio',                icon: (s) => <FaDatabase size={s} />          },
  { label: 'Slack',                icon: (s) => <SiSlack size={s} />             },
  { label: 'Claude Code',          icon: (s) => <SiAnthropic size={s} />         },
  { label: 'ChatGPT',              icon: (s) => <SiOpenai size={s} />            },
  { label: 'Influencer Marketing', icon: (s) => <FaLayerGroup size={s} />        },
  { label: 'Sales Funnels',        icon: (s) => <FaFunnelDollar size={s} />      },
  { label: 'UI/UX',                icon: (s) => <FaPaintBrush size={s} />        },
  { label: 'AI UGC',               icon: (s) => <FaRobot size={s} />             },
];
